Coordinator
all:
	javac *.java

coord:
	java Coordinator ../configFiles/coordinatorConfig.txt

part1:
	java Participant ../configFiles/p1.txt
    
part2:
	java Participant ../configFiles/p2.txt

clean:
	rm -f *.class
